onboarding = false

[theme]
name = "rose-pine-dawn"

[theme.custom]
panel_bg = "reset"

[experimental]
kitty_graphics = true

[keys]
switch_workspace = "ctrl+shift+1..9"
previous_workspace = "prefix+{"
next_workspace = "prefix+}"
focus_pane_left = "shift+alt+left"
focus_pane_down = "shift+alt+down"
focus_pane_up = "shift+alt+up"
focus_pane_right = "shift+alt+right"
split_horizontal = "prefix+minus"
split_vertical = "prefix+v"
close_pane = ""
swap_pane_left = "ctrl+shift+left"
swap_pane_down = "ctrl+shift+down"
swap_pane_up = "ctrl+shift+up"
swap_pane_right = "ctrl+shift+right"

[[keys.command]]
key = "cmd+shift+p"
type = "plugin_action"
command = "seigi.command-palette.open"
description = "command palette"

[[keys.command]]
key = "prefix+space"
type = "plugin_action"
command = "seigi.command-palette.open"
description = "command palette"

[[keys.command]]
key = "prefix+x"
type = "plugin_action"
command = "seigi.command-palette.smart_close"
description = "close pane, then tab, but keep workspace"

[ui]
prompt_new_tab_name = false
