onboarding = false
[theme] # Built-in themes: catppuccin, terminal, tokyo-night, dracula, nord, # gruvbox, one-dark, solarized, kanagawa, rose-pine, # vesper
# name = "catppuccin"

[experimental]
kitty_graphics = true
